/** Design tokens — sourced from Wireframe matchread-spec/css/tokens.css */

export const color = {
  canvas: "#FFFFFF",
  raised: "#F2F5F4",
  sunken: "#FAFBFB",
  line: "#E2E7E6",
  lineStrong: "#C9D1CF",
  lineControl: "#828E8B",
  textPrimary: "#15181B",
  textSecondary: "#3B4248",
  textMuted: "#626A72",
  inverse: "#15181B",
  inverseText: "#FFFFFF",
  read: "#15181B",
  readStrong: "#3B4248",
  data: "#0A6B42",
  dataStrong: "#053D26",
  wta: "#C6A2FF",
  miss: "#C93F36",
  missStrong: "#A8322A",
  courtClay: "#C2633C",
  courtGrass: "#5F8F3A",
  courtHard: "#2F6FA8",
  courtIndoor: "#293D5E",
} as const;

export const font = {
  display: 'Archivo, ui-sans-serif, system-ui, sans-serif',
  body: '"Instrument Sans", ui-sans-serif, system-ui, sans-serif',
  numeral: '"IBM Plex Mono", ui-monospace, monospace',
} as const;

export const spacing = {
  none: "0px",
  xs: "4px",
  sm: "8px",
  md: "12px",
  lg: "16px",
  xl: "20px",
  "2xl": "24px",
  "3xl": "32px",
  "4xl": "40px",
  "5xl": "56px",
} as const;

/** Emit CSS custom properties for :root */
export function cssVariables(): string {
  return [
    `--mr-canvas: ${color.canvas}`,
    `--mr-raised: ${color.raised}`,
    `--mr-sunken: ${color.sunken}`,
    `--mr-line: ${color.line}`,
    `--mr-line-strong: ${color.lineStrong}`,
    `--mr-line-control: ${color.lineControl}`,
    `--mr-text-primary: ${color.textPrimary}`,
    `--mr-text-secondary: ${color.textSecondary}`,
    `--mr-text-muted: ${color.textMuted}`,
    `--mr-inverse: ${color.inverse}`,
    `--mr-inverse-text: ${color.inverseText}`,
    `--mr-read: ${color.read}`,
    `--mr-read-strong: ${color.readStrong}`,
    `--mr-data: ${color.data}`,
    `--mr-data-strong: ${color.dataStrong}`,
    `--mr-wta: ${color.wta}`,
    `--mr-miss: ${color.miss}`,
    `--mr-miss-strong: ${color.missStrong}`,
    `--mr-court-clay: ${color.courtClay}`,
    `--mr-court-grass: ${color.courtGrass}`,
    `--mr-court-hard: ${color.courtHard}`,
    `--mr-court-indoor: ${color.courtIndoor}`,
    `--mr-font-display: ${font.display}`,
    `--mr-font-body: ${font.body}`,
    `--mr-font-numeral: ${font.numeral}`,
    `--s-none: ${spacing.none}`,
    `--s-xs: ${spacing.xs}`,
    `--s-sm: ${spacing.sm}`,
    `--s-md: ${spacing.md}`,
    `--s-lg: ${spacing.lg}`,
    `--s-xl: ${spacing.xl}`,
    `--s-2xl: ${spacing["2xl"]}`,
    `--s-3xl: ${spacing["3xl"]}`,
    `--s-4xl: ${spacing["4xl"]}`,
    `--s-5xl: ${spacing["5xl"]}`,
    `--max-prose: 680px`,
    `--max-content: 1180px`,
    `--touch: 44px`,
  ].join("; ");
}
