/* =========================================================================
   build-docs.js — emit the written deliverables from the registry.
   -------------------------------------------------------------------------
   The screen inventory, the interaction specification and the engineer mapping
   are generated from js/registry.js rather than written beside it. That is the
   same discipline apps/web/app/showcase applies to the design system: a
   document maintained by hand next to the artefact it describes is a document
   that will disagree with it inside a month.

   Run:  node tools/build-docs.js      (Node 18+, no dependencies)
   ========================================================================= */

const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const sandbox = { window: {} };
sandbox.window.MR = {};
global.MR = sandbox.window.MR;
global.window = sandbox.window;

eval(fs.readFileSync(path.join(root, 'js/registry.js'), 'utf8'));

const R = global.MR.registry;
const STATUS = global.MR.STATUS_LABEL;
const MVP = { mvp: 'Launch MVP', post: 'Post Launch', explor: 'Visual Exploration' };

const GROUPS = ['Entry', 'Leagues', 'Tournament', 'Public', 'System', 'Operator', 'Daily picks (not on web)'];
const esc = (s) => String(s).replace(/\|/g, '\\|').replace(/\n/g, ' ');

const HEAD = (title, sub) => `# MatchRead — ${title}

**US Open 2026 web launch.** ${sub}

> Generated from \`js/registry.js\` by \`tools/build-docs.js\`. Do not edit this file by
> hand — edit the registry and regenerate, or the prototype and the document will
> disagree within a month.

---

`;

/* ------------------------------------------------------------ 1. inventory */

let inv = HEAD('Screen Inventory',
  'Every screen, its purpose, how it is reached, what it needs, and whether it is in the launch.');

inv += `## Summary\n\n| Classification | Screens |\n|---|---|\n`;
for (const k of ['mvp', 'post', 'explor']) {
  inv += `| ${MVP[k]} | ${R.filter((s) => s.mvp === k).length} |\n`;
}
inv += `| **Total** | **${R.length}** |\n\n`;

inv += `| Implementation status | Screens |\n|---|---|\n`;
for (const k of ['exists', 'partial', 'needs', 'future']) {
  inv += `| ${STATUS[k]} | ${R.filter((s) => s.mapping.status === k).length} |\n`;
}
inv += `\n---\n\n`;

for (const g of GROUPS) {
  const rows = R.filter((s) => s.group === g);
  if (!rows.length) continue;
  inv += `## ${g}\n\n`;
  for (const s of rows) {
    inv += `### ${s.name}\n\n`;
    inv += `| | |\n|---|---|\n`;
    inv += `| **Route** | \`${s.route}\` |\n`;
    inv += `| **Classification** | ${MVP[s.mvp]} |\n`;
    inv += `| **Implementation status** | ${STATUS[s.mapping.status]} |\n`;
    inv += `| **Interaction states** | ${s.states.length} — ${s.states.join(' · ')} |\n\n`;
    inv += `**Purpose.** ${s.purpose}\n\n`;
    inv += `**Entry points**\n\n${s.entry.map((e) => `- ${e}`).join('\n')}\n\n`;
    inv += `**Exit points**\n\n${s.exit.map((e) => `- ${e}`).join('\n')}\n\n`;
    inv += `**Required data**\n\n${s.data.map((e) => `- ${e}`).join('\n')}\n\n`;
    inv += `---\n\n`;
  }
}

/* ---------------------------------------------------- 2. interaction spec */

let ints = HEAD('Interaction Specification',
  'Every interactive element: what it does, where it goes, and how it behaves when things are missing, slow or broken.');

const totalIx = R.reduce((n, s) => n + s.interactions.length, 0);
ints += `${totalIx} interactive elements across ${R.length} screens.\n\n---\n\n`;

for (const g of GROUPS) {
  const rows = R.filter((s) => s.group === g);
  if (!rows.length) continue;
  ints += `## ${g}\n\n`;
  for (const s of rows) {
    ints += `### ${s.name}  \n\`${s.route}\` · ${MVP[s.mvp]}\n\n`;
    for (const i of s.interactions) {
      ints += `#### ${i.name}\n\n`;
      ints += `\`${STATUS[i.status]}\`\n\n`;
      ints += `| Aspect | Specification |\n|---|---|\n`;
      ints += `| User action | ${esc(i.action)} |\n`;
      ints += `| Resulting behaviour | ${esc(i.behaviour)} |\n`;
      ints += `| Destination | ${esc(i.destination)} |\n`;
      ints += `| Required data | ${esc(i.data)} |\n`;
      ints += `| Disabled conditions | ${esc(i.disabled)} |\n`;
      ints += `| Loading behaviour | ${esc(i.loading)} |\n`;
      ints += `| Empty state | ${esc(i.empty)} |\n`;
      ints += `| Success state | ${esc(i.success)} |\n`;
      ints += `| Failure state | ${esc(i.failure)} |\n`;
      ints += `| Animation / transition | ${esc(i.motion)} |\n\n`;
    }
    ints += `---\n\n`;
  }
}

/* -------------------------------------------------------- 3. engineer map */

let eng = HEAD('Engineer Mapping',
  'For each screen: the probable existing route, the reusable component, the backend and database dependency, and what it actually costs.');

eng += `## The whole product, at a glance\n\n`;
eng += `| Screen | Route | Status | Class |\n|---|---|---|---|\n`;
for (const s of R) {
  eng += `| ${s.name} | \`${s.route}\` | ${STATUS[s.mapping.status]} | ${MVP[s.mvp]} |\n`;
}
eng += `\n---\n\n`;

eng += `## What is not built\n\nEvery item below is classified **Needs Engineering** and is on the launch path.\n\n`;
for (const s of R.filter((x) => x.mapping.status === 'needs')) {
  eng += `- **${s.name}** — ${s.mapping.notes}\n`;
}
const partialIx = [];
for (const s of R) {
  for (const i of s.interactions) if (i.status === 'needs') partialIx.push(`${s.name} → ${i.name}`);
}
eng += `\nIndividual interactions on otherwise-shipped screens that need engineering:\n\n`;
eng += partialIx.map((x) => `- ${x}`).join('\n') + '\n\n---\n\n';

for (const g of GROUPS) {
  const rows = R.filter((s) => s.group === g);
  if (!rows.length) continue;
  eng += `## ${g}\n\n`;
  for (const s of rows) {
    const m = s.mapping;
    eng += `### ${s.name}\n\n`;
    eng += `| | |\n|---|---|\n`;
    eng += `| **Implementation status** | **${STATUS[m.status]}** |\n`;
    eng += `| Probable existing route | \`${m.route}\` |\n`;
    eng += `| Reusable component | \`${m.component}\` |\n`;
    eng += `| Backend dependency | ${esc(m.backend)} |\n`;
    eng += `| Required database | \`${m.database}\` |\n`;
    eng += `| Expected API interaction | ${esc(m.api)} |\n\n`;
    eng += `**Notes.** ${m.notes}\n\n---\n\n`;
  }
}

fs.mkdirSync(path.join(root, 'docs'), { recursive: true });
fs.writeFileSync(path.join(root, 'docs/SCREEN-INVENTORY.md'), inv);
fs.writeFileSync(path.join(root, 'docs/INTERACTION-SPEC.md'), ints);
fs.writeFileSync(path.join(root, 'docs/ENGINEER-MAPPING.md'), eng);

console.log(`screens        ${R.length}`);
console.log(`interactions   ${totalIx}`);
console.log(`states         ${R.reduce((n, s) => n + s.states.length, 0)}`);
console.log('wrote docs/SCREEN-INVENTORY.md, docs/INTERACTION-SPEC.md, docs/ENGINEER-MAPPING.md');
